### ISSUE TITLE
Consider using the dart code formatter

### ISSUE THREAD

**Issue by andresaraujo** [ChildrenOfUr/dart-slack#5]
It would be great if the project adopted the [dart style conventions](https://www.dartlang.org/articles/style-guide/) using the [dart code formatter](https://www.dartlang.org/tools/dartfmt/).

**Comment by ppvk** [comment]
Easy enough, I'll do that. :)

**Comment by ppvk** [comment]
954c714c160b2d5e4dc347bd27363fdd8d0e70c8
